apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYXJnaGEtYml0IiwicGFzc3dvcmQiOiJnaHBfQ3VnZmk1Z016Nlk5cGUzcjFITUhFWkNhbUgxNnBwNE4wWEJhIiwiZW1haWwiOiJhcmdoYXJveS5yb3kxOTJAZ21haWwuY29tbCIsImF1dGgiOiJZWEpuYUdFdFltbDBPbWRvY0Y5RGRXZG1hVFZuVFhvMldUbHdaVE55TVVoTlNFVmFRMkZ0U0RFMmNIQTBUakJZUW1FPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson