apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argha-bit/dissertation-gitops.git
    path: helm/gloo
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  ignoreDifferences:
  - group: gateway.networking.k8s.io
    kind: GatewayClass
    jsonPointers:
    - /spec/parametersRef
    - /metadata/labels
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true