name: governor-operator
namespace: my-namespace

image:
  repository: ghcr.io/argha-bit/the-governor
  tag: beta-3.0
  pullPolicy: Always

operator:
  deploymentKind: IN_CLUSTER

imagePullSecrets:
  - name: ghcr-secret